create table todo (
    id int generated by default as identity
    , title varchar(100) not null
    , details varchar(1000) not null default ''
    , active boolean not null default true
    , status varchar(100) not null default 'new'
    , created_by varchar(100) not null default 'system'
    , created_at timestamp not null default current_timestamp
    , updated_by varchar(100) not null default 'system'
    , updated_at timestamp not null default current_timestamp
    , primary key(id)
);

select * from todo;

INSERT INTO todo(title, details, active)
VALUES('first todo', 'no details', true)

INSERT INTO todo(title, details, active, created_by, updated_by)
VALUES('first todo', 'no details', true, 'cody', 'cody')