# Generated by Django 4.1.1 on 2022-10-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todolist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='important',
            new_name='is_important',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
