# Generated by Django 4.1.1 on 2022-10-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_datecompleted_todo_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['title']},
        ),
    ]
