create table account (
    id int generated by default as identity,
    name varchar(100) not null,
    active boolean not null default true,
    balance dec(15, 2) not null,
    primary key(id)
);

insert into account(name, balance)
values('Don Nod', 400000);

insert into account(name, balance)
values('Bob Ross', 400000);

insert into account(name, balance)
values('PoorStranger', -50);

select * from account;
